spring:
 datasource:
  url: jdbc:mysql://localhost:3306/pos_db
  username: root
  password: admin
 jpa:
  hibernate:
   ddl-auto: create
  properties:
   hibernate:
    '[show_sql]': true
    '[format_sql]': true
   
  
  
